import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@shopify/polaris/build/esm/styles.css';
import { PolarisProvider } from "./PolarisProvider";
import { AppProvider } from "./ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PolarisProvider>
          <AppProvider>
            {children}
          </AppProvider>
        </PolarisProvider>
      </body>
    </html >
  );
}
